# Generated by Django 2.0 on 2018-01-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmas_happiness_engine', '0002_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='memory',
            field=models.CharField(max_length=100000),
        ),
    ]
