# Generated by Django 2.0 on 2018-01-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmas_happiness_engine', '0003_auto_20180101_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='memory_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='xmas_happiness_engine.Memory'),
        ),
    ]
