# Generated by Django 2.0 on 2018-01-27 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmas_happiness_engine', '0004_auto_20180101_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='memory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xmas_happiness_engine.Memory'),
        ),
    ]
